### PR TITLE
Accommodate MP water for the HERMES data

### PR DESCRIPTION
**Pull request by muhammadsaleh87**
Some modifications to accommodate MP water for the HERMES data

### CODE REVIEW

**Comment by schorschinho** [comment]
@HJZollner I suggest we test and accept the changes pertaining to accepting the water plot changes.
Less sure about the custom output folder for LCM raw files since it might break the existing LCModel integration (and would not comply with BIDS-style derivatives).
Also, need to not accept the GUI/SPMPath thing

**Comment by HJZollner** [comment]
Great! I quite like the idea. Also great to see that loading different sequence types seem to work fine. However, the combination of the subspectra into a single water file can be done using the function combine_water_subspecs and I am also not sure about the hasRef if case after combining the water subspectra (How does having an ecc reference affect the eddy current correction of the short-TE water spectrum?). Any chance you could supply me a test dataset @muhammadsaleh87 ? 

Second @schorschinho about the integration of the LCM control file changes. We either want modeling of edited data to be fully integrated using the established functionalities for conventional data or we leave it up to the user to use their own scripts to do the LCModel analysis.

Will pull some of the changes after ISMRM.

**Comment by muhammadsaleh87** [comment]
Hi Helge:

Thanks for looking into this issue. I have attached the job file, and the
link to an example dataset (HERMES suppressed and MP unsuppressed data) is
below. This dataset also did not align NAA properly post-RobustSpecReg
(attached).

Link:
https://drive.google.com/drive/folders/1GcjlHFm_RFCDTyqSL9oDO6AhA1rYX79J?usp=sharing

Regards
Muhammad Saleh

**Comment by muhammadsaleh87** [comment]
Hi Helge:

Both would be fantastic, especially the different fit ranges.

Thank you
Muhammad Saleh

**Pull request closed without merging**
